// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllHotelsHandlerFunc turns a function with the right signature into a get all hotels handler
type GetAllHotelsHandlerFunc func(GetAllHotelsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllHotelsHandlerFunc) Handle(params GetAllHotelsParams) middleware.Responder {
	return fn(params)
}

// GetAllHotelsHandler interface for that can handle valid get all hotels params
type GetAllHotelsHandler interface {
	Handle(GetAllHotelsParams) middleware.Responder
}

// NewGetAllHotels creates a new http.Handler for the get all hotels operation
func NewGetAllHotels(ctx *middleware.Context, handler GetAllHotelsHandler) *GetAllHotels {
	return &GetAllHotels{Context: ctx, Handler: handler}
}

/*GetAllHotels swagger:route GET /hotels/all getAllHotels

Get all hotels

*/
type GetAllHotels struct {
	Context *middleware.Context
	Handler GetAllHotelsHandler
}

func (o *GetAllHotels) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllHotelsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
