// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Hotel API
This is a simple hotel API


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    Contact: <eugene.toropov@gmail.com>

    Consumes:
    - application/io.goswagger.hotels.v1+json

    Produces:
    - application/io.goswagger.hotels.v1+json

swagger:meta
*/
package restapi
